name = "MTRconnect-Universal26"
author = "Kardosadam"
version = "2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c00c7fc2d91abccb85f915844c2229ec7c0af21412205ccf41ba6b6e46466151"

[versions]
fabric = "0.19.2"
minecraft = "1.20.1"
