name = "MTRconnect-Universal26"
author = "Kardosadam"
version = "2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0b9c5f6385e742523dec0559a0c436801a527a73f03d921eafb23bc6bbce4831"

[versions]
fabric = "0.19.2"
minecraft = "1.20.1"
