name = "MTRconnect-Universal26"
author = "Kardosadam"
version = "2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bf514ea24c7b33cee7b23b667e3dbc11411298a03b0760dbadcaf7e072b1400d"

[versions]
fabric = "0.19.2"
minecraft = "1.20.1"
